version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: nutrirecipe_db
    environment:
      POSTGRES_USER: nutrirecipe
      POSTGRES_PASSWORD: nutrirecipe
      POSTGRES_DB: nutrirecipe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
